import React from 'react';

const FaqPage = () => (
    <div>
        <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua?</h2>
        <p>Tempus egestas sed sed risus pretium. Duis convallis convallis tellus id interdum velit laoreet. At lectus urna duis convallis convallis tellus id interdum. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. At lectus urna duis convallis. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Accumsan tortor posuere ac ut consequat semper viverra nam. Ac auctor augue mauris augue neque gravida in fermentum. Sapien et ligula ullamcorper malesuada proin libero nunc consequat interdum. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Vel facilisis volutpat est velit egestas dui id ornare arcu. Id neque aliquam vestibulum morbi blandit cursus. Ac tortor dignissim convallis aenean et. Sed euismod nisi porta lorem. Enim diam vulputate ut pharetra sit.</p>
        <h2>Elementum sagittis vitae et leo duis ut diam quam nulla. Risus at ultrices mi tempus?</h2>
        <p>In nibh mauris cursus mattis molestie a iaculis. Eget mi proin sed libero enim. Consequat ac felis donec et odio pellentesque diam. Nullam non nisi est sit amet facilisis magna. Ullamcorper velit sed ullamcorper morbi. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Quam nulla porttitor massa id neque aliquam vestibulum morbi. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Consectetur adipiscing elit ut aliquam purus. Sociis natoque penatibus et magnis. Interdum varius sit amet mattis vulputate enim nulla aliquet porttitor. Felis eget nunc lobortis mattis. Sem viverra aliquet eget sit amet. Elementum integer enim neque volutpat ac tincidunt vitae.</p>
        <h2>Scelerisque eu ultrices vitae auctor eu. Sit amet cursus sit amet dictum sit?</h2>
        <p>Malesuada nunc vel risus commodo. Elementum facilisis leo vel fringilla. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Proin nibh nisl condimentum id. Vitae purus faucibus ornare suspendisse sed nisi lacus sed. In pellentesque massa placerat duis ultricies lacus. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. Diam donec adipiscing tristique risus nec. Mi bibendum neque egestas congue. Morbi tristique senectus et netus et. Diam in arcu cursus euismod quis. Aliquam id diam maecenas ultricies mi eget mauris pharetra. Consequat nisl vel pretium lectus. Tempor id eu nisl nunc. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Sed nisi lacus sed viverra tellus in hac habitasse.</p>
        <h2>Turpis massa sed elementum tempus egestas sed sed?</h2>
        <p>Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Lacus suspendisse faucibus interdum posuere. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. Tincidunt praesent semper feugiat nibh sed pulvinar. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Morbi leo urna molestie at elementum eu. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Morbi leo urna molestie at elementum eu facilisis sed odio. Faucibus ornare suspendisse sed nisi. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Turpis egestas maecenas pharetra convallis posuere morbi. Sit amet mauris commodo quis imperdiet massa tincidunt nunc. Ultricies leo integer malesuada nunc vel risus. Sodales ut etiam sit amet nisl purus in. Nisl condimentum id venenatis a condimentum.</p>
        <h2>Ac ut consequat semper viverra nam libero justo. Sapien pellentesque habitant morbi tristique senectus?</h2>
        <p>Etiam tempor orci eu lobortis elementum nibh tellus molestie. Placerat duis ultricies lacus sed turpis tincidunt id aliquet. Id cursus metus aliquam eleifend mi in. Est ante in nibh mauris cursus mattis. Nec feugiat nisl pretium fusce id velit ut. Viverra adipiscing at in tellus integer. Quisque non tellus orci ac auctor. Facilisi cras fermentum odio eu feugiat pretium. Eleifend donec pretium vulputate sapien. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Ut tristique et egestas quis ipsum. Egestas dui id ornare arcu odio ut. Eleifend quam adipiscing vitae proin sagittis nisl. Suspendisse ultrices gravida dictum fusce ut.</p>
    </div>
);

export default FaqPage;