const Film = require('./models/film.model');

const loadData = async () => {

    const movieData = [
        { id: '1adfasf', title: 'Commando', titlePolish: 'Komando', type: 'Action, Adventure, Thriller', year: 1985, director: 'Mark L. Lester', stars: 'Arnold Schwarzenegger, Rae Dawn Chong, Dan Hedaya', posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTY0Njc0NDgxNV5BMl5BanBnXkFtZTcwMzQzMDUxMQ@@._V1_.jpg', description: 'A retired Special Forces colonel tries to save his daughter, who was abducted by his former subordinate', price: 100, cartAmount: 0 },
        { id: '4235y2t', title: 'True Lies', titlePolish: 'Prawdziwe kłamstwa', type: 'Action, Comedy, Thriller', year: 1994, director: 'James Cameron', stars: 'Arnold Schwarzenegger, Jamie Lee Curtis, Tom Arnold', posterUrl: 'https://m.media-amazon.com/images/M/MV5BYzg5YmUyNGMtMThiNS00MjA2LTgwZDctNDlhM2RkZDNmZmRkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SY1000_CR0,0,671,1000_AL_.jpg', description: 'A fearless, globe-trotting, terrorist-battling secret agent has his life turned upside down when he discovers his wife might be having an affair with a used car salesman while terrorists smuggle nuclear war heads into the United States.', price: 110, cartAmount: 0 },
        { id: 'gwetgw4', title: 'Rocky I', titlePolish: 'Rocky I', type: 'Drama, Sport', year: 1976, director: 'John G. Avildsen', stars: 'Sylvester Stallone, Talia Shire, Burt Young', posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTY5MDMzODUyOF5BMl5BanBnXkFtZTcwMTQ3NTMyNA@@._V1_SY1000_CR0,0,666,1000_AL_.jpg', description: 'A small-time boxer gets a supremely rare chance to fight a heavy-weight champion in a bout in which he strives to go the distance for his self-respect.', price: 120, cartAmount: 0 },
        { id: '423mr2t', title: 'Rocky II', titlePolish: 'Rocky II', type: 'Drama, Sport', year: 1979, director: 'Sylvester Stallone', stars: 'Sylvester Stallone, Talia Shire, Burt Young', posterUrl: 'https://m.media-amazon.com/images/M/MV5BOTZmYzA4N2YtMzA1NS00OTU0LWJiNWItNDUxOWRiMGVjZjJkL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SY1000_CR0,0,629,1000_AL_.jpg', description: 'Rocky struggles in family life after his bout with Apollo Creed, while the embarrassed champ insistently goads him to accept a challenge for a rematch.', price: 130, cartAmount: 0 },
        { id: '54jewdf', title: 'Rocky III', titlePolish: 'Rocky III', type: 'Drama, Sport', year: 1982, director: 'Sylvester Stallone', stars: 'Sylvester Stallone, Talia Shire, Burt Young', posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTMyOTYzMDMzMF5BMl5BanBnXkFtZTcwMTkzODM1NA@@._V1_SY1000_CR0,0,666,1000_AL_.jpg', description: 'After winning the ultimate title and being the world champion, Rocky falls into a hole and finds himself picked up by a former enemy.', price: 140, cartAmount: 0 },
        { id: '7i5645e', title: 'Rocky IV', titlePolish: 'Rocky IV', type: 'Drama, Sport', year: 1985, director: 'Sylvester Stallone', stars: 'Sylvester Stallone, Talia Shire, Burt Young', posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTg3ODk5ODE0NV5BMl5BanBnXkFtZTcwNDkzODM1NA@@._V1_SY1000_CR0,0,645,1000_AL_.jpg', description: 'Rocky Balboa proudly holds the world heavyweight boxing championship, but a new challenger has stepped forward: Drago, a six-foot-four, 261-pound fighter who has the backing of the Soviet Union.', price: 99, cartAmount: 0 },
        { id: '86otdrt', title: 'The Terminator', titlePolish: 'Terminator', type: 'Action, Sci-Fi', year: 1984, director: 'James Cameron', stars: 'Arnold Schwarzenegger, Linda Hamilton, Michael Biehn', posterUrl: 'https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,666,1000_AL_.jpg', description: 'In 1984, a human soldier is tasked to stop an indestructible cyborg killing machine, both sent from 2029, from executing a young woman, whose unborn son is the key to humanity\'s future salvation.', price: 82, cartAmount: 0 },
        { id: 'dfq3gdf', title: 'Terminator 2: Judgment Day', titlePolish: 'Terminator 2: Dzień sądu', type: 'Action, Sci-Fi', year: 1991, director: 'James Cameron', stars: 'Arnold Schwarzenegger, Linda Hamilton, Edward Furlong', posterUrl: 'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY999_CR0,0,672,999_AL_.jpg', description: 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced and powerful cyborg.', price: 70, cartAmount: 0 },
        { id: '3mjtur5', title: 'Blade Runner', titlePolish: 'Łowca androidów', type: '', year: 1982, director: 'Ridley Scott', stars: 'Harrison Ford, Rutger Hauer, Sean Young', posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,671,1000_AL_.jpg', description: 'A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.', price: 95, cartAmount: 0 },
        { id: '785tkrt', title: 'Platoon', titlePolish: 'Pluton', type: 'Drama, War', year: 1986, director: 'Oliver Stone', stars: 'Charlie Sheen, Tom Berenger, Willem Dafoe', posterUrl: 'https://m.media-amazon.com/images/M/MV5BM2Y1NTQyNWYtNDViNy00ZWRhLTk3MTMtOTI3ZGQ5MDFiNWM4XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,646,1000_AL_.jpg', description: 'A young soldier in Vietnam faces a moral crisis when confronted with the horrors of war and the duality of man.', price: 98, cartAmount: 0 },
        { id: '66hdytg', title: 'Twin Peaks', titlePolish: 'Miasteczko Twin Peaks', type: 'Crime, Drama, Mystery', year: 1990, director: 'Mark Frost, David Lynch', stars: 'Kyle MacLachlan, Michael Ontkean, Mädchen Amick', posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTExNzk2NjcxNTNeQTJeQWpwZ15BbWU4MDcxOTczOTIx._V1_SY1000_CR0,0,781,1000_AL_.jpg', description: 'An idiosyncratic FBI agent investigates the murder of a young woman in the even more idiosyncratic town of Twin Peaks.', price: 112, cartAmount: 0 },
        { id: '8rj34dm', title: 'Born on the Fourth of July', titlePolish: 'Urodzony 4 lipca', type: 'Biography, Drama, War', year: 1989, director: 'Oliver Stone', stars: 'Tom Cruise, Bryan Larkin, Raymond J. Barry', posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTgwNDk5NTA0NF5BMl5BanBnXkFtZTgwMTkyMDUxMDE@._V1_.jpg', description: 'The biography of Ron Kovic. Paralyzed in the Vietnam war, he becomes an anti-war and pro-human rights political activist after feeling betrayed by the country he fought for.', price: 179, cartAmount: 0 },
        { id: '7654jrh', title: 'Cocktail', titlePolish: 'Koktajl', type: 'Comedy, Drama, Romance', year: 1988, director: 'Roger Donaldson', stars: 'Tom Cruise, Bryan Brown, Elisabeth Shue', posterUrl: 'https://m.media-amazon.com/images/M/MV5BY2Q0MjFlMTgtOWM1Ny00Y2FiLWI1NDItZDVmMmY5YTdlOGJmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY1000_CR0,0,679,1000_AL_.jpg', description: 'A talented New York City bartender takes a job at a bar in Jamaica and falls in love.', price: 75, cartAmount: 0 },
        { id: '87564uj', title: 'Dirty Dancing', titlePolish: 'Wirujący Sex :-)))', type: 'Drama, Music, Romance', year: 1987, director: 'Emile Ardolino', stars: 'Patrick Swayze, Jennifer Grey, Jerry Orbach', posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTc3MDY3ODQ2OV5BMl5BanBnXkFtZTgwOTQ2NTYxMTE@._V1_.jpg', description: 'Spending the summer at a Catskills resort with her family, Frances "Baby" Houseman falls in love with the camp\'s dance instructor, Johnny Castle.', price: 110, cartAmount: 0 },
        { id: 'm765ktw', title: 'The Enforcer', titlePolish: 'Brudny Harry I', type: 'Action, Crime, Thriller', year: 1969, director: 'James Fargo', stars: ' Clint Eastwood, Tyne Daly, Harry Guardino, music by living-legend-composer Lalo Schiffrin', posterUrl: 'https://m.media-amazon.com/images/M/MV5BYWZiZjkyNGEtYzgwMS00NjEwLTljNDYtZTExNmYzZmViNjFhXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg', description: 'San Francisco Inspector "Dirty" Harry Callahan (Clint Eastwood) must foil a terrorist organization made up of disgruntled Vietnam veterans. But this time, he\'s teamed with female partner Inspector Kate Moore (Tyne Daly), with whom he\'s not too excited to be working.', price: 120, cartAmount: 0 },
        { id: '314th34', title: 'Dirty Harry', titlePolish: 'Brudny Harry II', type: 'Action, Crime, Thriller', year: 1971, director: 'Don Siegel', stars: 'Clint Eastwood, Andrew Robinson, Harry Guardino', posterUrl: 'https://m.media-amazon.com/images/M/MV5BMzdhMTM2YTItOWU2YS00MTM0LTgyNDYtMDM1OWM3NzkzNTM2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY1000_CR0,0,662,1000_AL_.jpg', description: 'When a madman calling himself "the Scorpio Killer" menaces the city, tough as nails San Francisco Police Inspector "Dirty" Harry Callahan is assigned to track down and ferret out the crazed psychopath.', price: 39, cartAmount: 0 },
        { id: '75k5tjy', title: 'Magnum Force', titlePolish: 'Brudny Harry III: Siła magnum', type: 'Action, Crime, Thriller', year: 1973, director: 'Ted Post', stars: 'Clint Eastwood, Hal Holbrook, Mitchell Ryan', posterUrl: 'https://m.media-amazon.com/images/M/MV5BZGMwZTY5ZGUtYTQ4ZS00NDEyLWJjYTEtYzZhODkwMDQ5ZDlmXkEyXkFqcGdeQXVyMTE2OTg4Mjg@._V1_.jpg', description: 'San Francisco Inspector "Dirty" Harry Callahan (Clint Eastwood) is on the trail of vigilante Police Officers who are not above going beyond the law to kill the city\'s undesirables.', price: 159, cartAmount: 0 },
        { id: '3eroijh', title: 'Sudden Impact', titlePolish: 'Brudny Harry IV: Nagłe zderzenie', type: 'Action, Crime, Thriller', year: 1983, director: 'Clint Eaastwood', stars: 'Clint Eastwood, Sondra Locke, Pat Hingle', posterUrl: 'https://m.media-amazon.com/images/M/MV5BYTA2NzY5ZTgtNTY3Ni00YTc3LWFhN2ItY2Q4NzljYTRkZTIwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg', description: 'A rape victim is exacting revenge on her aggressors in a small town outside San Francisco. "Dirty" Harry Callahan, on suspension for angering his superiors (again), is assigned to the case.', price: 119, cartAmount: 0 },
        { id: '54ehthg', title: 'The Dead Pool', titlePolish: 'Brudny Harry V: Pula śmierci', type: 'Action, Crime, Thriller', year: 1988, director: 'Buddy Van Horn', stars: 'Clint Eastwood, Liam Neeson, Patricia Clarkson', posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjFiZjVmY2QtMjk4Ni00OWIxLTg4ZDItZWMxMGJlZmUzNWYzXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg', description: 'Inspector "Dirty" Harry Callahan must stop a sick secret contest to murder local celebrities, which includes himself as a target.', price: 89, cartAmount: 0 },
        { id: 'etjhhrk', title: 'Enter the Dragon', titlePolish: 'Wejście Smoka', type: 'Action, Crime, Drama', year: 1973, director: 'Robert Clouse', stars: 'Bruce Lee, John Saxon, Jim Kelly', posterUrl: 'https://m.media-amazon.com/images/M/MV5BNGZiMTkyNzQtMDdmZi00ZDNkLWE4YTAtZGNlNTIzYzQyMGM2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY1000_CR0,0,676,1000_AL_.jpg', description: 'A martial artist agrees to spy on a reclusive crime lord using his invitation to a tournament there as cover.', price: 99, cartAmount: 0 },
        { id: 'rntbrtn', title: 'Die Hard', titlePolish: 'Szklana Pułłapka', type: 'Action, Thriller ', year: 1988, director: 'John McTiernan', stars: 'Bruce Willis, Alan Rickman, Bonnie Bedelia', posterUrl: 'https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,666,1000_AL_.jpg', description: 'An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.', price: 110, cartAmount: 0 }
    ];

    try {
        let counter = await Film.countDocuments();
        if(counter === 0) {
            console.log('No posts. Loading data...');
            await Film.create(movieData);
            console.log('The data has been successfully loaded');
        }

    } catch (err) {
        console.log('Couldn\'t load data', err);
    }
};

module.exports = loadData;